# Generated by Django 5.0.2 on 2024-10-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
