# Generated by Django 5.0.2 on 2024-10-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
